# -*- mode: ruby -*-
# vi: set ft=ruby :
ENV['VAGRANT_SERVER_URL'] = 'https://vagrant.elab.pro'

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/20.04"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "test"

    vb.gui = false

    vb.memory = "2048"

    vb.cpus = 1
  end

  config.vm.hostname = "amir"

  config.vm.synced_folder ".", "/home/vagrant/code",
owner: "vagrant", group: "vagrant"

  config.vm.network "public_network"

  config.vm.provision "shell", path: "provision.sh"
end